name: wa_tanpa_simpan_nomor
description: A simple Flutter app to send WA messages without saving number.

# Aplikasi ini tidak diterbitkan ke pub.dev
publish_to: 'none'

# Versi aplikasi
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ikon iOS-style
  cupertino_icons: ^1.0.2

  # Google AdMob SDK untuk banner ads
  google_mobile_ads: ^4.0.0

  # Untuk membuka WhatsApp melalui URL intent
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter untuk menjaga kualitas kode
  flutter_lints: ^3.0.0

  # Untuk generate ikon aplikasi
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Gambar ikon harus diletakkan di sini
  assets:
    - assets/icon.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
