name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - run: flutter pub get

      # Tambahkan langkah generate icon
      - run: flutter pub run flutter_launcher_icons:main

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: wa-tanpa-simpan-nomor-apk
          path: build/app/outputs/flutter-apk/app-release.apk
